export const dynamic = 'force-dynamic'

import Link from 'next/link'
import { createServiceClient } from '@/lib/supabase/server'
import { timeAgo } from '@/lib/timeAgo'
import { TASK_AGENT } from '@/lib/agent/roles'

// Artifact Gallery: エージェントが生んだ成果物（レポート・サイト・商品）の画廊
// 現状は3つの公開サイト + CEO/CXOレポートを時系列Masonry表示

const PUBLIC_SITES = [
  {
    type: 'site' as const,
    title: 'Patent Mining Spain 🇪🇸',
    subtitle: 'USPTO patents → Amazon.es FBA',
    url: 'https://www.amazon.es/s?me=PENDING_SELLER_ID',
    color: '#ef4444',
    createdAt: '2026-05-14T00:00:00Z',
  },
  {
    type: 'site' as const,
    title: 'DigitalSouq',
    subtitle: 'Notion & Canva templates — Arabic professionals',
    url: 'https://roboco-op.gumroad.com',
    color: '#a855f7',
    createdAt: '2026-05-14T00:00:00Z',
  },
  {
    type: 'site' as const,
    title: 'AI Sales Buddy',
    subtitle: 'B2B lead capture & demo booking SaaS',
    url: 'https://pronto-ai-sales-buddy.lovable.app/',
    color: '#f59e0b',
    createdAt: '2026-05-14T00:00:00Z',
  },
]


async function getArtifacts() {
  try {
    const supabase = createServiceClient()
    const [runsRes, startupsRes] = await Promise.all([
      supabase
        .from('agent_runs')
        .select('*')
        .not('result', 'is', null)
        .order('created_at', { ascending: false })
        .limit(40),
      supabase.from('startups').select('id, name'),
    ])
    const startupMap = Object.fromEntries(
      (startupsRes.data ?? []).map((s: { id: string; name: string }) => [s.id, s])
    )
    return { runs: runsRes.data ?? [], startupMap }
  } catch {
    return { runs: [], startupMap: {} }
  }
}

export default async function ArtifactsPage() {
  const { runs, startupMap } = await getArtifacts()

  return (
    <div className="flex flex-col min-h-0 overflow-auto">
      <div className="px-6 py-4 border-b border-[#1c1c22] flex items-center justify-between shrink-0">
        <div>
          <h1 className="text-[15px] font-semibold tracking-tight">Artifacts</h1>
          <p className="text-[11px] text-zinc-600 mt-0.5">Artifacts generated by agents</p>
        </div>
        <div className="flex items-center gap-3 text-[11px] text-zinc-600 font-mono">
          <span>{PUBLIC_SITES.length} sites</span>
          <span>·</span>
          <span>{runs.length} reports</span>
        </div>
      </div>

      <div className="flex-1 px-6 py-5 space-y-6">
        {/* 公開サイト */}
        <section>
          <p className="text-[10px] text-zinc-500 font-semibold uppercase tracking-[0.1em] mb-3">Live Sites</p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            {PUBLIC_SITES.map((s, i) => (
              <a
                key={s.url}
                href={s.url}
                target="_blank"
                rel="noopener noreferrer"
                className="card p-0 overflow-hidden hover:border-[#27272a] transition-all group animate-fade-in"
                style={{ animationDelay: `${i * 60}ms` }}
              >
                <div
                  className="h-28 flex items-center justify-center relative overflow-hidden"
                  style={{
                    background: `linear-gradient(135deg, ${s.color}30 0%, ${s.color}10 100%)`,
                  }}
                >
                  <div
                    className="absolute inset-0 opacity-30"
                    style={{
                      backgroundImage: `radial-gradient(circle at 20% 30%, ${s.color}40 0%, transparent 60%)`,
                    }}
                  />
                  <div
                    className="text-[24px] font-black tracking-tight relative z-10"
                    style={{ color: s.color, filter: `drop-shadow(0 0 8px ${s.color})` }}
                  >
                    {s.title}
                  </div>
                </div>
                <div className="p-3">
                  <p className="text-[11px] text-zinc-400">{s.subtitle}</p>
                  <p className="text-[10px] text-zinc-600 mt-1 truncate font-mono">
                    {s.url.replace('https://', '')}
                  </p>
                  <div className="flex items-center justify-between mt-2 pt-2 border-t border-[#1c1c22]">
                    <span className="text-[9px] px-1.5 py-0.5 rounded bg-green-500/10 text-green-400 font-mono">
                      LIVE
                    </span>
                    <span className="text-[10px] text-zinc-500 group-hover:text-purple-400 transition-colors flex items-center gap-1">
                      Visit
                      <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                      </svg>
                    </span>
                  </div>
                </div>
              </a>
            ))}
          </div>
        </section>

        {/* レポート */}
        <section>
          <p className="text-[10px] text-zinc-500 font-semibold uppercase tracking-[0.1em] mb-3">Reports & Analyses</p>
          {runs.length === 0 ? (
            <div className="card p-8 text-center">
              <p className="text-[12px] text-zinc-600">No reports yet</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
              {runs.map((run: { id: string; task_type?: string | null; startup_id?: string | null; cost_usd?: number | null; created_at: string; result?: string | null }, i: number) => {
                const agent = run.task_type ? TASK_AGENT[run.task_type] : null
                const taskLabel = agent?.taskLabel ?? run.task_type ?? 'Task'
                const startup = run.startup_id ? startupMap[run.startup_id] : null
                const preview = typeof run.result === 'string'
                  ? run.result.slice(0, 280).replace(/[#*_]/g, '').trim()
                  : ''
                return (
                  <Link
                    key={run.id}
                    href={agent ? `/dashboard/agents/${agent.role}` : '#'}
                    className="card p-4 hover:border-[#27272a] transition-all group relative overflow-hidden animate-fade-in"
                    style={{ animationDelay: `${Math.min(i, 30) * 30}ms` }}
                  >
                    {agent && (
                      <div
                        className="absolute top-0 right-0 w-20 h-20 rounded-full -mr-10 -mt-10 opacity-10 blur-2xl"
                        style={{ backgroundColor: agent.color }}
                      />
                    )}
                    <div className="flex items-center justify-between mb-2 relative">
                      {agent ? (
                        <div
                          className="flex items-center gap-1.5 text-[10px] px-1.5 py-0.5 rounded font-bold"
                          style={{ backgroundColor: agent.color + '20', color: agent.color }}
                        >
                          {agent.label}
                          <span className="text-zinc-500 font-normal">· {taskLabel}</span>
                        </div>
                      ) : (
                        <span className="text-[10px] text-zinc-600 font-mono">{taskLabel}</span>
                      )}
                      <span className="text-[10px] text-zinc-700 font-mono">
                        {timeAgo(run.created_at)}
                      </span>
                    </div>
                    {startup && (
                      <p className="text-[10px] text-zinc-500 mb-2">· {startup.name}</p>
                    )}
                    <p className="text-[11px] text-zinc-400 line-clamp-5 leading-relaxed relative">
                      {preview}
                      {preview.length >= 280 && '...'}
                    </p>
                    <div className="mt-3 pt-2 border-t border-[#1c1c22] flex items-center justify-between relative">
                      <span className="text-[9px] text-zinc-700 font-mono">
                        ${Number(run.cost_usd || 0).toFixed(4)}
                      </span>
                      <span className="text-[10px] text-zinc-500 group-hover:text-purple-400 transition-colors">
                        Read full →
                      </span>
                    </div>
                  </Link>
                )
              })}
            </div>
          )}
        </section>
      </div>
    </div>
  )
}
