#!/usr/bin/env bash
# StartupRobos — one-time operator initialization
# Inspired by OpenFisca's country-template/first-time-setup.sh
#
# Run this ONCE after creating your instance from the StartupRobos template.
# It walks you through setting up .env.local, generating secrets, and writing
# a personalized README for your instance.

set -euo pipefail

cd "$(dirname "$0")/.."

bold() { printf '\033[1m%s\033[0m\n' "$1"; }
dim()  { printf '\033[2m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }
red() { printf '\033[31m%s\033[0m\n' "$1"; }

# -------- Safety check --------
if [[ -f .env.local ]]; then
  yellow "⚠️  .env.local already exists. Rerunning init-operator.sh will NOT overwrite it."
  yellow "    If you want a fresh setup, delete .env.local first."
  read -r -p "Continue anyway (README + businesses will still be updated)? [y/N] " cont
  [[ "$cont" =~ ^[Yy]$ ]] || exit 0
fi

# -------- Detect instance context --------
bold "📦 StartupRobos — Operator Init"
dim "This will personalize your instance with your operator details."
echo

INSTANCE_REMOTE="$(git config --get remote.origin.url 2>/dev/null || echo '')"
INSTANCE_DEFAULT_NAME="$(basename -s .git "$INSTANCE_REMOTE" 2>/dev/null || echo 'startuprobos')"

if [[ -z "$INSTANCE_REMOTE" ]]; then
  red "No git remote found. Did you clone your instance from the template?"
  red "Expected: https://github.com/YOUR_USERNAME/your-instance-name.git"
  exit 1
fi

if [[ "$INSTANCE_REMOTE" == *"Robo-Co-op/StartupRobos"* ]]; then
  red "You seem to be running this inside the StartupRobos framework repo itself."
  red "This script is for operator instances created via 'Use this template'."
  red "Aborting to prevent corruption of the framework."
  exit 1
fi

# -------- Prompt: operator identity --------
read -r -p "Your name (how should the AI call you?): " OPERATOR_NAME
read -r -p "Your email (for CEO daily reports) [NOTIFY_EMAIL]: " OPERATOR_EMAIL
read -r -p "Monthly AI budget in USD: " MONTHLY_BUDGET
if [[ -z "$MONTHLY_BUDGET" ]]; then
  red "Monthly budget is required."
  exit 1
fi

# -------- Prompt: Supabase --------
echo
bold "🗄  Supabase"
dim "Create a free project at https://supabase.com first, then paste values below."
dim "Settings → API gives you these three."
read -r -p "Supabase Project URL (https://xxx.supabase.co): " SUPABASE_URL
read -r -p "Supabase anon key: " SUPABASE_ANON
read -r -s -p "Supabase service role key (hidden): " SUPABASE_SERVICE
echo
echo

# -------- Prompt: Anthropic --------
bold "🤖 Anthropic"
dim "Get your key at https://console.anthropic.com → API Keys"
read -r -s -p "Anthropic API key (hidden): " ANTHROPIC_KEY
echo
echo

# -------- Generate secrets --------
bold "🔐 Generating secrets"
API_SECRET="$(openssl rand -hex 32)"
CRON_SECRET="$(openssl rand -hex 32)"
green "  API_SECRET:   (generated)"
green "  CRON_SECRET:  (generated)"
echo

# -------- Write .env.local --------
if [[ ! -f .env.local ]]; then
  cat > .env.local <<EOF
# StartupRobos — generated by scripts/init-operator.sh on $(date -u +%FT%TZ)

# Supabase
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE}

# Anthropic
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}

# API authentication
API_SECRET=${API_SECRET}
CRON_SECRET=${CRON_SECRET}

# Email notifications (set RESEND_API_KEY after creating a Resend account)
RESEND_API_KEY=
NOTIFY_EMAIL=${OPERATOR_EMAIL}

# App
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF
  green "✓ .env.local written"
else
  dim "· .env.local already exists — skipped"
fi

# -------- Personalize README --------
bold "📝 Personalizing README"
INSTANCE_NAME="$INSTANCE_DEFAULT_NAME"
cat > OPERATOR.md <<EOF
# ${INSTANCE_NAME} — operator notes

This is an instance of [StartupRobos](https://github.com/Robo-Co-op/StartupRobos) owned by **${OPERATOR_NAME}**.

- Monthly AI budget: \$${MONTHLY_BUDGET}
- Reports delivered to: ${OPERATOR_EMAIL}
- Initialized: $(date -u +%FT%TZ)

## Next steps
1. Run Supabase schema: paste \`supabase/schema.sql\` + \`supabase/migrations/001_spend_budget_rpc.sql\` into Supabase SQL Editor
2. Deploy to Vercel: \`npx vercel\` then \`npx vercel env add\` for each var in \`.env.local\`
3. Open Claude Code: \`claude\` — the AI will pick your 3 businesses

## Staying up to date
\`\`\`bash
git remote add upstream https://github.com/Robo-Co-op/StartupRobos.git
git fetch upstream
git merge upstream/main
\`\`\`
EOF
green "✓ OPERATOR.md written"

# -------- Final instructions --------
echo
bold "🎉 Init complete"
echo
green "Next steps:"
echo "  1. Run Supabase SQL:    paste supabase/schema.sql into Supabase SQL Editor"
echo "  2. Run migration SQL:   paste supabase/migrations/001_spend_budget_rpc.sql"
echo "  3. Deploy to Vercel:    npx vercel && npx vercel env add"
echo "  4. Open Claude Code:    claude"
echo
dim "Details in OPERATOR.md and README.md."
